package com.myskoolclub.backend.model;

public enum NotificationType {
    SCHOOL_REQUEST_SUBMITTED,
    SCHOOL_MEMBERSHIP_REQUESTED,
    SCHOOL_MEMBERSHIP_APPROVED,
    SCHOOL_MEMBERSHIP_REJECTED,
    SCHOOL_MEMBERSHIP_REVOKED,
    SCHOOL_ADMIN_ASSIGNED,
    CLUB_MEMBERSHIP_REQUESTED,
    CLUB_MEMBERSHIP_APPROVED,
    CLUB_MEMBERSHIP_REJECTED,
    CLUB_MEMBERSHIP_REVOKED,
    CLUB_ADMIN_ASSIGNED,
    INVOICE_SUBMITTED,
    INVOICE_APPROVED,
    INVOICE_SENT_BACK,
    INVOICE_PAID,
    INVOICE_CANCELLED,
    INVENTORY_CHECKED_IN,
    CONTENT_REPORT_SUBMITTED
}
